services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3310:3310"
      - "3000:3000"
    environment:
      NODE_ENV: development
      APP_PORT: 3310
      APP_SECRET: "development-only-secret-at-least-32-characters"
      CLIENT_URL: "http://localhost:3000"
      DATABASE_URL: "postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-lucarne}"
      VITE_API_URL: "http://localhost:3310"
    command: sh -c "npm run prisma:generate && npm run dev"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME:-lucarne}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5435}
        host_ip: 127.0.0.1
        protocol: tcp

  db_test:
    profiles:
      - test
    image: postgres:17
    environment:
      POSTGRES_DB: ${TEST_DB_NAME:-lucarne_test}
      POSTGRES_USER: ${TEST_DB_USER:-test_user}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-test_password}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: ${POSTGRES_TEST_PORT:-5436}
        host_ip: 127.0.0.1
        protocol: tcp

volumes:
  postgres_data:
  postgres_test_data:
