import { APP_ROLES } from "../../auth/appRole";

const TEAM_CREATE_ROLES = [
  APP_ROLES.ADMIN,
  APP_ROLES.MODERATOR,
  APP_ROLES.EDITOR,
] as const;
const TEAM_VIEW_ROLES = TEAM_CREATE_ROLES;
const TEAM_EDIT_ROLES = [APP_ROLES.ADMIN, APP_ROLES.EDITOR] as const;

export { TEAM_CREATE_ROLES, TEAM_EDIT_ROLES, TEAM_VIEW_ROLES };
